version: '3'
services:
  web:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "18623:8000"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:8000", "app.wsgi"]
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "5"